version: '3.9'

services:
  mc:
    image: itzg/minecraft-server:java17-alpine
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
    volumes:
      - ./minecraft_data:/data

  cloudflared:
    image: cloudflare/cloudflared:2022.6.3
    command: tunnel run
    env_file:
      - .env