version: '3.9'

services:
  cloudflared:
    image: cloudflare/cloudflared:2022.7.1
    command: tunnel --config /config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
      - ./config.yml/:/config.yml:ro
  

  apache:
    image: httpd:2.4-alpine
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html:ro